runtime: go
env: flex
api_version: 1

automatic_scaling:
  min_num_instances: 1

##[START env_variables]
#env_variables:
#  GCLOUD_DATASET_ID: nbolsa-calculus
#    GCLOUD_STORAGE_BUCKET: ibex35
#      PROJECT_ID: nbolsa-calculus
##[END env_variables]
# [END runtime]